/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-env.d.ts --include-runtime false --config wrangler.jsonc` (hash: 9507d3d5e998d48ccc2b7aa0b59eb51c)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
