/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-env.d.ts --include-runtime false --config wrangler.jsonc` (hash: b02a01c7dc3b4b2eebe3fd0593523e16)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	GITHUB_SYNC_QUEUE: Queue;
	AVC_ACCESS_TEAM_DOMAIN: "mertz.cloudflareaccess.com";
	AVC_ACCESS_AUD: "875efad6b43955c6a936e44b379a3074a7bd71f7309e8539cda974f4d39d0681";
	AVC_OAUTH_ORIGIN: "https://journey.peter-s-mertz.workers.dev";
	AVC_GITHUB_CLIENT_ID: "";
	AVC_GITLAB_CLIENT_ID: "";
	AVC_AUTH_MODE: "password";
	GITHUB_SYNC_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AVC_ACCESS_TEAM_DOMAIN" | "AVC_ACCESS_AUD" | "AVC_OAUTH_ORIGIN" | "AVC_GITHUB_CLIENT_ID" | "AVC_GITLAB_CLIENT_ID" | "AVC_AUTH_MODE" | "GITHUB_SYNC_KEY">> {}
}
