import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const root=process.env.AVC_TEST_URL??'http://127.0.0.1:4173';let cookie='';
async function request(path,body,token,expected=200){const r=await fetch(root+path,{method:body?'POST':'GET',headers:{...(cookie&&!token?{Cookie:cookie}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const d=await r.json();assert.equal(r.status,expected,JSON.stringify(d));return d.result??d;}
const identity=crypto.randomUUID().slice(0,8);await request('/api/auth',{action:'register',email:`test-${identity}@example.com`,password:'local-test-password-2026'});
const {project}=await request('/api/avc',{action:'create_project',name:'HTTP protocol test'});const a=await request('/api/avc',{action:'create_agent',project,name:'Agent A'}),b=await request('/api/avc',{action:'create_agent',project,name:'Agent B'});
const act=(action,body={},auth,expected=200)=>request('/api/avc',{action,project,requestId:crypto.randomUUID(),...body},auth,expected);
const state=async(auth)=> (await request('/api/avc?project='+project,undefined,auth)).state;
const ja=await act('create_journey',{title:'Lookup errors',description:'Change the missing-user contract'},a.token),jb=await act('create_journey',{title:'Format display name',description:'Trim display names'},b.token);
const ca=await act('create_changeset',{journey:ja.journey,description:'Make errors explicit'},a.token),cb=await act('create_changeset',{journey:jb.journey,description:'Trim names'},b.token);
let s=await state(a.token);const original=s.head;
const la=await act('acquire',{journey:ja.journey,changeset:ca.changeset,revision:original,scopes:[{path:'src/users.rs',start:6,end:13}]},a.token);
const lb=await act('acquire',{journey:jb.journey,changeset:cb.changeset,revision:original,scopes:[{path:'src/users.rs',start:15,end:17}]},b.token);
assert.equal(la.queued,false);assert.equal(lb.queued,false);
const views=await state(a.token);assert(views.leases.find(l=>l.journey===ja.journey).token);assert.equal(views.leases.find(l=>l.journey===jb.journey).token,undefined);
await act('record',{journey:ja.journey,kind:'command',provenance:'captured',description:'Check initial tests',command:'cargo test',output:'test result: ok',exitCode:0},a.token);
const recording=(await request(`/api/avc?project=${project}&journey=${ja.journey}`,undefined,a.token)).events.find(e=>e.type==='recording.recorded');assert.equal(recording.data.provenance,'captured');
const snapshot=await request(`/api/avc?project=${project}&revision=${original}`,undefined,a.token);
const contentA=snapshot.files['src/users.rs'].replace('-> Option<User>','-> Result<User, String>').replace('Some(User { id, name: "Ada".into() })','Ok(User { id, name: "Ada".into() })').replace('        None','        Err("not found".into())');
const contentB=snapshot.files['src/users.rs'].replace('user.name.clone()','user.name.trim().to_string()');
await act('patch',{journey:ja.journey,changeset:ca.changeset,revision:original,description:'Out-of-scope attempt',edits:[{path:'README.md',content:'bad'}],tokens:la.locks.map(l=>l.token)},a.token,409);
const patchA={action:'patch',project,journey:ja.journey,changeset:ca.changeset,revision:original,description:'Return lookup errors',edits:[{path:'src/users.rs',content:contentA}],tokens:la.locks.map(l=>l.token),requestId:crypto.randomUUID()};
const pa=await request('/api/avc',patchA,a.token);const retry=await request('/api/avc',patchA,a.token);assert.deepEqual(pa,retry);await request('/api/avc',{...patchA,description:'Changed payload'},a.token,409);
const pb=await act('patch',{journey:jb.journey,changeset:cb.changeset,revision:original,description:'Trim display names',edits:[{path:'src/users.rs',content:contentB}],tokens:lb.locks.map(l=>l.token)},b.token);
await act('submit',{journey:ja.journey,revision:pa.revision,tokens:la.locks.map(l=>l.token)},a.token,409);
await act('declare_breaking',{journey:ja.journey,changes:[{target:'find_user',kind:'signature',before:'Option<User>',after:'Result<User, String>',migration:'Handle lookup errors.'}]},a.token);
await act('submit',{journey:ja.journey,revision:pa.revision,tokens:la.locks.map(l=>l.token)},a.token);
await act('review',{journey:ja.journey,revision:pa.revision,kind:'approve',body:'Not allowed'},a.token,403);
await act('review',{journey:ja.journey,revision:pa.revision,kind:'request_changes',body:'Document the return contract'});
let j=(await state()).journeys.find(j=>j.id===ja.journey);await act('resolve_review',{journey:ja.journey,review:j.reviews[0].id},a.token);
await act('review',{journey:ja.journey,revision:pa.revision,kind:'approve',body:'Reviewed'});
await act('declare_breaking',{journey:ja.journey,changes:[{target:'find_user',kind:'signature',before:'Option<User>',after:'Result<User, String>',migration:'Handle lookup errors.'}]},a.token);
await act('submit',{journey:ja.journey,revision:pa.revision,tokens:la.locks.map(l=>l.token)},a.token);
await act('integrate',{journey:ja.journey,revision:pa.revision,head:original,cursor:0,tokens:la.locks.map(l=>l.token)},a.token,409);
await act('review',{journey:ja.journey,revision:pa.revision,kind:'approve',body:'Re-approved updated contract'});
const integrated=await act('integrate',{journey:ja.journey,revision:pa.revision,head:original,cursor:0,tokens:la.locks.map(l=>l.token)},a.token);
const inbox=await request(`/api/avc?project=${project}&journey=${jb.journey}&since=0`,undefined,b.token);const event=inbox.events.find(e=>e.type==='journey.integrated');assert.equal(event.data.breakingChanges[0].target,'find_user');
await request(`/api/avc?project=${project}&journey=${jb.journey}`,undefined,a.token,403);
await act('declare_breaking',{journey:jb.journey,changes:[]},b.token);
await act('submit',{journey:jb.journey,revision:pb.revision,tokens:lb.locks.map(l=>l.token)},b.token,409);
s=await state(b.token);const reconciled=await act('reconcile',{journey:jb.journey,head:s.head,cursor:s.integrationCursor,dispositions:{[event.id]:'unaffected'}},b.token);
await act('declare_breaking',{journey:jb.journey,changes:[]},b.token);await act('submit',{journey:jb.journey,revision:reconciled.revision,tokens:lb.locks.map(l=>l.token)},b.token);await act('review',{journey:jb.journey,revision:reconciled.revision,kind:'approve',body:'Reviewed combined changes'});
s=await state(b.token);await act('integrate',{journey:jb.journey,revision:reconciled.revision,head:s.head,cursor:s.integrationCursor,tokens:lb.locks.map(l=>l.token)},b.token);
s=await state();assert.equal(s.leases.length,0);assert(s.journeys.every(j=>j.status==='integrated'));
const final=await request(`/api/avc?project=${project}&revision=${s.head}`,undefined,a.token);assert(final.files['src/users.rs'].includes('Result<User, String>'));assert(final.files['src/users.rs'].includes('trim().to_string()'));
const dir=mkdtempSync(join(tmpdir(),'avc-clone-'));execFileSync('git',['clone','--quiet',root+'/api/git/'+project+'/',dir],{env:{...process.env,GIT_CONFIG_COUNT:'1',GIT_CONFIG_KEY_0:'http.extraHeader',GIT_CONFIG_VALUE_0:'Authorization: Bearer '+a.token},stdio:['ignore','pipe','pipe']});assert.equal(readFileSync(join(dir,'src/users.rs'),'utf8'),final.files['src/users.rs']);execFileSync('git',['-C',dir,'fsck','--no-dangling'],{stdio:['ignore','pipe','pipe']});
console.log('HTTP protocol smoke passed: two agents, coverage rejection, idempotency, human review, breaking-change delivery, reconciliation, atomic integration and authenticated Git clone.');
