import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {deflateSync} from 'node:zlib';
import {diff,applyHunks,remap,mergeFiles,acquire,recordPatch,expire,validateSubmission,finalizeIntegration,checkTokens} from '../lib/avc/core.ts';
import {makeCommit} from '../lib/avc/git.ts';
const base='a\nb\nc\nd\ne\nf\ng\nh\ni';
function fixture(){const j={id:'j1',title:'Feature',description:'Feature',actor:'a',status:'working',base:'base',head:'base',reconciledHead:'base',reconciledCursor:0,changesets:[{id:'c1',description:'Step',patches:[]}],manifest:[],manifestDeclared:false,reviews:[],dispositions:{},created:0};const s={id:'p',name:'P',head:'base',revisions:{},journeys:[j],leases:[],waiting:[],events:[],sequence:0,integrationCursor:0,generation:0,receipts:{},requireApproval:true};return {s,j};}
test('multi-hunk diff reconstructs file and handles empty and repeated lines',()=>{for(const [a,b]of [['','x'],[base,'a\nB\nc\nd\ne\nf\nG\nh\ni'],['x\nx\ny\n','x\ny\nx\n'],['abc','']])assert.equal(applyHunks(a,diff(a,b)),b);});
test('version-anchored ranges shift after unrelated insertion',()=>{assert.deepEqual(remap(4,7,diff(base,'new\n'+base)),[5,8]);assert.throws(()=>remap(1,3,diff(base,'a\nB\nc\nd\ne\nf\ng\nh\ni')),/anchored range changed/);});
test('disjoint edits merge; same-region edits conflict',()=>{const ours={f:'a\nB\nc\nd\ne\nf\ng\nh\ni'},theirs={f:'a\nb\nc\nd\ne\nf\nG\nh\ni'};assert.equal(mergeFiles({f:base},ours,theirs).f,'a\nB\nc\nd\ne\nf\nG\nh\ni');assert.throws(()=>mergeFiles({f:base},ours,{f:'a\nother\nc\nd\ne\nf\ng\nh\ni'}),/anchored range changed/);});
test('overlap queues, expiry emits notification, stale generations cannot publish',()=>{const {s,j}=fixture();const j2={...structuredClone(j),id:'j2',actor:'b'};s.journeys.push(j2);const first=acquire(s,j,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'a',1000);const queued=acquire(s,j2,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'b',1000);assert.equal(queued.queued,true);expire(s,601001);assert(s.events.some(e=>e.type==='lock.available'&&e.targets.includes('j2')));const next=acquire(s,j2,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'b',601001);assert(next.locks[0].generation>first.locks[0].generation);assert.throws(()=>checkTokens(s,j2,[first.locks[0].token],601001),/every current/);});
test('atomic acquisition does not partially grant a multi-scope request',()=>{const {s,j}=fixture();const j2={...structuredClone(j),id:'j2'};s.journeys.push(j2);acquire(s,j,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'a',0);const result=acquire(s,j2,'c1',[{path:'f',start:5,end:6},{path:'f',start:2,end:3}],'base',{f:base},{f:base},'b',0);assert(result.queued);assert(!s.leases.some(l=>l.journey==='j2'));});
test('partial holders cannot wait for conflicting additional scopes',()=>{const {s,j}=fixture();const j2={...structuredClone(j),id:'j2'};s.journeys.push(j2);acquire(s,j,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'a',0);acquire(s,j2,'c1',[{path:'f',start:6,end:7}],'base',{f:base},{f:base},'b',0);assert.throws(()=>acquire(s,j2,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'b',0),/Cannot wait/);});
test('patches require changeset coverage and preserve prior patches',()=>{const {s,j}=fixture();const grant=acquire(s,j,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'a',0);const tokens=grant.locks.map(l=>l.token);assert.throws(()=>recordPatch(s,j,'c1',{f:base+'\nx'},{f:base},'new','Bad edit','a',tokens,1),/unlocked/);const p=recordPatch(s,j,'c1',{f:'a\nB\nc\nd\ne\nf\ng\nh\ni'},{f:base},'new','Edit','a',tokens,1);assert.equal(p.before,'base');assert.equal(j.head,'new');assert.equal(j.changesets[0].patches.length,1);assert.equal(j.manifestDeclared,false);assert.equal(s.leases.length,1);});
test('submission requires explicit declaration and current integration cursor',()=>{const {s,j}=fixture();j.changesets[0].patches.push({id:'p'});assert.throws(()=>validateSubmission(s,j),/Declare breaking/);j.manifestDeclared=true;validateSubmission(s,j);s.head='accepted';s.integrationCursor=12;assert.throws(()=>validateSubmission(s,j),/Reconcile/);});
test('integration releases only the completed journey locks and notifies open journeys',()=>{const {s,j}=fixture();s.journeys.push({...structuredClone(j),id:'j2'});s.leases.push({journey:'j1',id:'l1'},{journey:'j2',id:'l2',whole:true});const e=finalizeIntegration(s,j,'new','a',{f:base},{f:base});assert.equal(s.head,'new');assert.equal(j.status,'integrated');assert.equal(s.leases.length,1);assert(e.targets.includes('j2'));assert.equal(s.integrationCursor,e.id);});
test('generated blobs, trees and commits are readable by real Git',async()=>{const dir=mkdtempSync(join(tmpdir(),'avc-git-'));execFileSync('git',['init','--bare',dir]);const c=await makeCommit({'src/a.rs':'pub fn a() {}\n','README.md':'hello\n'},undefined,'First commit','Tester',1700000000000);for(const o of c.objects){const parent=join(dir,'objects',o.oid.slice(0,2));mkdirSync(parent,{recursive:true});writeFileSync(join(parent,o.oid.slice(2)),deflateSync(o.raw));}execFileSync('git',['--git-dir',dir,'update-ref','refs/heads/main',c.oid]);assert.equal(execFileSync('git',['--git-dir',dir,'show',c.oid+':src/a.rs'],{encoding:'utf8'}),'pub fn a() {}\n');assert.equal(execFileSync('git',['--git-dir',dir,'fsck','--no-dangling'],{encoding:'utf8'}).trim(),'');});

test('successive changesets may reserve the same journey-owned scope',()=>{const {s,j}=fixture();j.changesets.push({id:'c2',description:'Correction',patches:[]});const a=acquire(s,j,'c1',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'a',0);const b=acquire(s,j,'c2',[{path:'f',start:2,end:3}],'base',{f:base},{f:base},'a',0);recordPatch(s,j,'c2',{f:'a\nB\nc\nd\ne\nf\ng\nh\ni'},{f:base},'new','Correct the same scope','a',[...a.locks,...b.locks].map(l=>l.token),1);assert.equal(j.changesets[1].patches.length,1);assert.equal(s.leases.length,2);});
