#!/usr/bin/env node
import {readFile} from 'node:fs/promises';
const root=process.env.AVC_URL?.replace(/\/$/,'');const project=process.env.AVC_PROJECT;const token=process.env.AVC_TOKEN;
if(!root||!project||!token){process.stderr.write('Set AVC_URL, AVC_PROJECT and AVC_TOKEN. For private Sites, also set AVC_SITE_SERVICE_TOKEN.\n');process.exit(1);}
const headers={'Authorization':`Bearer ${token}`,...(process.env.AVC_SITE_SERVICE_TOKEN?{'OAI-Sites-Authorization':`Bearer ${process.env.AVC_SITE_SERVICE_TOKEN}`}:{})};
const [command,...args]=process.argv.slice(2);
async function get(query={}){const url=new URL(root+'/api/avc');url.search=new URLSearchParams({project,...query}).toString();const res=await fetch(url,{headers});const data=await res.json();if(!res.ok)throw new Error(data.error);return data;}
async function post(body){const request={project,requestId:crypto.randomUUID(),...body};const payload=JSON.stringify(request);for(let retry=0;retry<3;retry++){try{const res=await fetch(root+'/api/avc',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:payload});const data=await res.json();if(res.status>=500&&retry<2)continue;if(!res.ok)throw new Error(JSON.stringify(data));return data.result??data;}catch(e){if(retry===2)throw e;}}}
try{if(command==='state')console.log(JSON.stringify(await get(),null,2));else if(command==='inbox')console.log(JSON.stringify(await get({journey:args[0],since:args[1]??'0'}),null,2));else if(command==='poll'){let cursor=args[1]??'0';for(;;){const d=await get({journey:args[0],since:cursor});for(const e of d.events)console.log(JSON.stringify(e));cursor=String(d.cursor);await new Promise(r=>setTimeout(r,3000));}}
else if(command==='keepalive'){for(;;){const {state}=await get();const tokens=state.leases.filter(l=>l.journey===args[0]&&l.token).map(l=>l.token);if(!tokens.length)throw new Error('No current leases remain; reacquire before publishing.');console.log(JSON.stringify(await post({action:'refresh',journey:args[0],tokens})));await new Promise(r=>setTimeout(r,60000));}}
else if(command==='record'){const body=JSON.parse(await readFile(args[1],'utf8'));console.log(JSON.stringify(await post({...body,action:'record',journey:args[0]}),null,2));}
else if(command==='request'){const body=JSON.parse(await readFile(args[0],'utf8'));console.log(JSON.stringify(await post(body),null,2));}
else if(command==='patch'){const [journey,changeset,path,file,description]=args;const {state}=await get();const j=state.journeys.find(j=>j.id===journey);if(!j)throw new Error('Journey not found.');console.log(JSON.stringify(await post({action:'patch',journey,changeset,revision:j.head,description,edits:[{path,content:await readFile(file,'utf8')}],tokens:state.leases.filter(l=>l.journey===journey&&l.token).map(l=>l.token)}),null,2));}
else throw new Error('Commands: record <journey> <json-file> | state | request <json-file> | inbox <journey> [cursor] | poll <journey> [cursor] | keepalive <journey> | patch <journey> <changeset> <repo-path> <local-file> <description>');}catch(e){process.stderr.write(e.message+'\n');process.exit(1);}
